src/Entity/ExamSubject.php
<?php

namespace App\Entity;

use App\Repository\ExamSubjectRepository;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ExamSubjectRepository::class)
 */
class ExamSubject
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $course_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $the_mention;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $level;

    /**
     * @ORM\Column(type="string", length=4)
     * @Assert\NotBlank
     * @Assert\Regex(
     *     pattern="/(1|2)[0-9]{3}/",
     *     match=true,
     *     message="Valeur non autorisée"
     * )
     */
    private $exam_year;

    /**
     * @return mixed
     */
    public function getExamYear()
    {
        return $this->exam_year;
    }

    /**
     * @param mixed $exam_year
     * @return ExamSubject
     */
    public function setExamYear($exam_year)
    {
        $this->exam_year = $exam_year;
        return $this;
    }

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $school_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCourseName(): ?string
    {
        return $this->course_name;
    }

    public function setCourseName(string $course_name): self
    {
        $this->course_name = $course_name;

        return $this;
    }

    public function getTheMention(): ?string
    {
        return $this->the_mention;
    }

    public function setTheMention(string $the_mention): self
    {
        $this->the_mention = $the_mention;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }



    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getSchoolName(): ?string
    {
        return $this->school_name;
    }

    public function setSchoolName(string $school_name): self
    {
        $this->school_name = $school_name;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getSlug():string{
        return (new Slugify())->slugify($this->course_name.$this->id.$this->description);
    }
}

src/Controller/ExamSubjectController.php
<?php

namespace App\Controller;

use App\Entity\ExamSubject;
use App\Entity\ExamSubjectSearch;
use App\Form\ExamSubjectFormType;
use App\Form\ExamSubjectSearchFormType;
use App\Repository\ExamSubjectRepository;
use App\Tools\UploadFile;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\EventListener\AbstractSessionListener;
use Symfony\Component\Notifier\Notification\Notification;
use Symfony\Component\Notifier\NotifierInterface;
use Symfony\Component\Routing\Annotation\Route;

class ExamSubjectController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    /**
     * ExamSubjectController constructor.
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/exam/subject", name="exam_subject")
     * @param Request $request
     * @param ExamSubjectRepository $repository
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(Request $request, ExamSubjectRepository $repository, PaginatorInterface $paginator): Response
    {
        $search = new ExamSubjectSearch();
        $form = $this->createForm(ExamSubjectSearchFormType::class, $search);
        $form->handleRequest($request);
        if($form->isSubmitted()){
            $pagination = $paginator->paginate(
                $repository->findSearchByQuery($search),
                $request->query->getInt('page', 1),
                15
            );

            return $this->render('exam_subject/index.html.twig', [
                'pagination'=>$pagination,
                'form_search' => $form->createView()
            ]);
        }
        $response = $this->render('exam_subject/index.html.twig', [
            'form_search' => $form->createView(),
            'pagination'=>false
        ]);
        $response->headers->set(AbstractSessionListener::NO_AUTO_CACHE_CONTROL_HEADER, true);
        $response->setCache([
            'max_age'=>3600,
            's_maxage'=>3600,
            'immutable'=>true,
            'last_modified'=>new \DateTime(),
        ]);
        return $response;
    }

    /**
     * @param NotifierInterface $notifier
     * @param Request $request
     * @param string $ebook_file_dir
     * @return Response
     * @Route("/exam/subject/new_exam_subject", name="new_exam_subject")
     */
    public function new_exam_subject(NotifierInterface $notifier, Request $request, string $ebook_file_dir):Response{
        $exam_subject = new ExamSubject();
        $form = $this->createForm(ExamSubjectFormType::class, $exam_subject);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $exam_subject->setCreatedAt(new \DateTime('now'));
            $uploadFile = new UploadFile();
            $filename = $uploadFile->loadEbookSubjectFile($form, $ebook_file_dir, $exam_subject->getSlug());
            $exam_subject->setFilename($filename);
            $this->entityManager->persist($exam_subject);
            $this->entityManager->flush();
            $notifier->send(new Notification("Merci pour votre contribution !", ['browser']));
            return $this->redirectToRoute('exam_subject');
        }
        return $this->render('exam_subject/new_exam_subject.html.twig', [
            'form'=>$form->createView()
        ]);
    }
}

templates/exam_subject/__exam_subject_card.html.twig
<div class="__card">
    <div class="__exam_image">
        <img src="{{ asset('images/svg_img/exam_subject.svg') }}" style="height: 100%;" class="card-img-top" alt="ad image">
        <div class="__description">
            <h6 class="__myPolice"><i class="fas fa-filter"></i> {{ exam.theMention }}</h6>
            <h6 class="__myPolice"><i class="fas fa-level-up-alt"></i>  {{ exam.level }}</h6>
            <h6 class="__myPolice"><i class="fas fa-calendar"></i> {{ exam.examYear }}</h6>
            <h6 class="__myPolice"><i class="fas fa-align-center"></i> {{ exam.description }}</h6>
            <h6 class="__myPolice"><i class="fas fa-school"></i> {{ exam.schoolName }}</h6>
        </div>
    </div>
    <div class="card_body">
        <h3>
            <a class="__myPolice" style="color: #0D47A1;" href="{{ asset('ebook_subject_files/'~exam.filename) }}" download>{{ exam.courseName }}</a>
        </h3>
    </div>
</div>

templates/exam_subject/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sujets d'examen{% endblock %}

{% block body %}
    <main class="__main_page_activities">
        <div class="__container_book">
            <div class="bg-light __response_box mt-4">
                {{ form_start(form_search, {'attr':{'class': '__form-1', 'action': path('exam_subject')}}) }}
                <div class="__form-1_column">{{ form_widget(form_search.course_name) }}</div>
                <div class="__form-1_Btn">
                    <button id="validate_btn_act" class="btn btn-block" type="submit"><i class="fas fa-search"></i></button>
                </div>
                {{ form_end(form_search) }}
            </div>
            <hr class="__line">
            {% for message in app.flashes('notification') %}
                <div class="alert-success __alert-success p-3" style="display: flex;">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
            <div class="__ebook_cat">
                <ul class="__list_group list-unstyled">
                    <li class="__list_group_item"><a href="{{ path('exam_subject') }}" class="__myPolice"><i class="fas fa-home"></i></a></li>
                    <li class="__list_group_item"><a href="{{ path('new_exam_subject') }}" class="__myPolice"><i class="fas fa-plus-square"></i> Ajoutez un sujet</a></li>
                </ul>
            </div>
            <p style="text-align: center;"><em class="text-muted">
                Cette plateforme est conçue pour la documentation permettant d'avoir accès aux anciens sujets d'examen. <br>
                Et chacun est libre
                d'ajouter des exercices au format pdf.
            </em></p>
            {% if pagination %}
                <hr class="__line">
                <p class="__myTitle">{{ pagination|length }} sujet(s) trouvé(s)</p>
                <div class="__block">
                    {% for exam_sub in pagination %}
                        {% include 'exam_subject/__exam_subject_card.html.twig' with {'exam':exam_sub} %}
                    {% endfor %}
                </div>
                <div class="__navigation">
                    <hr class="__line">
                    <div class="navigation">
                        {{ knp_pagination_render(pagination) }}
                    </div>
                </div>
            {% endif %}
        </div>
    </main>
    {% include '__footer.html.twig' %}
{% endblock %}

templates/exam_subject/new_exam_subject.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contribution nouveau sujet{% endblock %}
{% block body %}
    <div class="__container_form">
        <div class="formBox">
            <div class="__announcement"><h5><i class="fas fa-plus-square"></i> Ajouter un sujet</h5></div>
            {{ form_start(form) }}
            <div class="adRegisterRow">
                <div class="adInputColumn">
                    {{ form_label(form.course_name, "Donnez le nom de l'epreuve *") }}
                    {{ form_widget(form.course_name) }}
                    <small class="form-text">{{ form_errors(form.course_name) }}</small>
                </div>
                <div class="adInputColumn">
                    {{ form_label(form.the_mention, "Donnez la mention *") }}
                    {{ form_widget(form.the_mention) }}
                    <small class="form-text">{{ form_errors(form.the_mention) }}</small>
                </div>
            </div>
            <div class="adRegisterRow">
                <div class="adInputColumn">
                    {{ form_label(form.level, "Donnez le niveau *") }}
                    {{ form_widget(form.level) }}
                    <small class="form-text">{{ form_errors(form.level) }}</small>
                </div>
                <div class="adInputColumn">
                    {{ form_label(form.exam_year, "Donnez l'année de l'examen *") }}
                    {{ form_widget(form.exam_year) }}
                    <small class="form-text">{{ form_errors(form.exam_year) }}</small>
                </div>
                <div class="adInputColumn">
                    {{ form_label(form.school_name, "Donnez le nom de l'établissement *") }}
                    {{ form_widget(form.school_name) }}
                    <small class="form-text">{{ form_errors(form.school_name) }}</small>
                </div>
            </div>
            <div class="adRegisterRow">
                <div class="adInputColumn-1">
                    {{ form_label(form.filename, "Ajoutez le pdf *") }}
                    {{ form_widget(form.filename) }}
                    <small class="form-text">{{ form_errors(form.filename) }}</small>
                </div>
            </div>
            <div class="adRegisterRow">
                <div class="adInputColumn-1">
                    {{ form_label(form.description, "D'autres precisions (facultatif)") }}
                    {{ form_widget(form.description) }}
                    <small class="form-text">{{ form_errors(form.description) }}</small>
                </div>
            </div>
            <div class="newActRegisterRow">
                <button id="submit_btn" class="validate_btn btn btn-rounded btn-block" type="submit">Ajouter</button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    {% include '__footer.html.twig' %}
{% endblock %}