src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use App\Tools\EntityInfos;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CarRepository::class)
 */
class Car implements EntityInfos
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $car_brand;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $car_model;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fuel;

    /**
     * @ORM\Column(type="string", length=7)
     * @Assert\Regex(
     *     pattern="/[0-9]+$/",
     *     match=true,
     *     message="Valeur non autorisée, seulement des chiffres"
     * )
     */
    private $mileage;

    /**
     * @ORM\Column(type="string", length=4)
     * @Assert\Regex(
     *     pattern="/(1|2)[0-9]{3}/",
     *     match=true,
     *     message="Valeur non autorisée"
     * )
     * @Assert\NotBlank
     */
    private $car_year;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Regex(
     *     pattern="/[a-zA-Z]+/",
     *     match=true,
     *     message="Valeur non autorisée"
     * )
     * @Assert\Length(min=6, minMessage="Valeur non autorisé, minimum 6 caractère")
     */
    private $car_country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $car_class;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Regex(
     *     pattern="/\d+/",
     *     match=true,
     *     message="Valeur non autorisée"
     * )
     * @Assert\NotBlank
     */
    private $car_nb_places;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Regex(
     *     pattern="/\d+/",
     *     match=true,
     *     message="Valeur non autorisée"
     * )
     * @Assert\NotBlank
     */
    private $car_nb_doors;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $car_color;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $car_state;


    /**
     * @ORM\OneToMany(targetEntity=CarAdvantages::class, mappedBy="car", orphanRemoval=true, cascade={"persist"})
     */
    private $car_advantages;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=ParkAuto::class, inversedBy="vehicles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $park_auto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $transmission_type;

    /**
     * @ORM\OneToMany(targetEntity=CarImages::class, mappedBy="car", orphanRemoval=true, cascade={"persist"})
     */
    private $carImages;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern="/\d+/",
     *     match=true,
     *     message="Valeur non autorisée"
     * )
     * @Assert\NotBlank
     */
    private $car_price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sale_state;

    public function __construct()
    {
        $this->car_advantages = new ArrayCollection();
        $this->carImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCarBrand(): ?string
    {
        return $this->car_brand;
    }

    public function setCarBrand(string $car_brand): self
    {
        $this->car_brand = $car_brand;

        return $this;
    }

    public function getCarModel(): ?string
    {
        return $this->car_model;
    }

    public function setCarModel(string $car_model): self
    {
        $this->car_model = $car_model;

        return $this;
    }

    public function getFuel(): ?string
    {
        return $this->fuel;
    }

    public function setFuel(string $fuel): self
    {
        $this->fuel = $fuel;

        return $this;
    }

    public function getMileage(): ?string
    {
        return $this->mileage;
    }

    public function setMileage(string $mileage): self
    {
        $this->mileage = $mileage;

        return $this;
    }

    public function getCarYear(): ?string
    {
        return $this->car_year;
    }

    public function setCarYear(string $car_year): self
    {
        $this->car_year = $car_year;

        return $this;
    }

    public function getCarCountry(): ?string
    {
        return $this->car_country;
    }

    public function setCarCountry(string $car_country): self
    {
        $this->car_country = $car_country;

        return $this;
    }

    public function getCarClass(): ?string
    {
        return $this->car_class;
    }

    public function setCarClass(string $car_class): self
    {
        $this->car_class = $car_class;

        return $this;
    }

    public function getCarNbPlaces(): ?int
    {
        return $this->car_nb_places;
    }

    public function setCarNbPlaces(int $car_nb_places): self
    {
        $this->car_nb_places = $car_nb_places;

        return $this;
    }

    public function getCarNbDoors(): ?int
    {
        return $this->car_nb_doors;
    }

    public function setCarNbDoors(int $car_nb_doors): self
    {
        $this->car_nb_doors = $car_nb_doors;

        return $this;
    }

    public function getCarColor(): ?string
    {
        return $this->car_color;
    }

    public function setCarColor(string $car_color): self
    {
        $this->car_color = $car_color;

        return $this;
    }

    public function getCarState(): ?string
    {
        return $this->car_state;
    }

    public function setCarState(string $car_state): self
    {
        $this->car_state = $car_state;

        return $this;
    }

    public function getParkAuto(): ?ParkAuto
    {
        return $this->park_auto;
    }

    public function setParkAuto(?ParkAuto $park_auto): self
    {
        $this->park_auto = $park_auto;

        return $this;
    }

    /**
     * @return Collection|CarAdvantages[]
     */
    public function getCarAdvantages(): Collection
    {
        return $this->car_advantages;
    }

    public function addCarAdvantage(CarAdvantages $carAdvantage): self
    {
        if (!$this->car_advantages->contains($carAdvantage)) {
            $this->car_advantages[] = $carAdvantage;
            $carAdvantage->setCar($this);
        }

        return $this;
    }

    public function removeCarAdvantage(CarAdvantages $carAdvantage): self
    {
        if ($this->car_advantages->removeElement($carAdvantage)) {
            // set the owning side to null (unless already changed)
            if ($carAdvantage->getCar() === $this) {
                $carAdvantage->setCar(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getTransmissionType(): ?string
    {
        return $this->transmission_type;
    }

    public function setTransmissionType(string $transmission_type): self
    {
        $this->transmission_type = $transmission_type;

        return $this;
    }

    /**
     * @return Collection|CarImages[]
     */
    public function getCarImages(): Collection
    {
        return $this->carImages;
    }

    public function addCarImage(CarImages $carImage): self
    {
        if (!$this->carImages->contains($carImage)) {
            $this->carImages[] = $carImage;
            $carImage->setCar($this);
        }

        return $this;
    }

    public function removeCarImage(CarImages $carImage): self
    {
        if ($this->carImages->removeElement($carImage)) {
            // set the owning side to null (unless already changed)
            if ($carImage->getCar() === $this) {
                $carImage->setCar(null);
            }
        }

        return $this;
    }

    public function getCarPrice(): ?string
    {
        return $this->car_price;
    }

    public function setCarPrice(string $car_price): self
    {
        $this->car_price = $car_price;

        return $this;
    }

    public function getSlug():string{
        return (new Slugify())->slugify($this->car_brand);
    }

    public function getSaleState(): ?bool
    {
        return $this->sale_state;
    }

    public function setSaleState(bool $sale_state): self
    {
        $this->sale_state = $sale_state;

        return $this;
    }

    public function getInfos(): array
    {
        $carImages = $this->getCarImages();
        $carAdges = $this->getCarAdvantages();
        $infos = [];
        foreach ($this as $item=>$value){
            if($item != "park_auto" and $item != "car_advantages" and $item!="carImages") {
                $infos[$item] = $value;
            }
        }
        $filename = [];
        foreach ($carImages as $image){
            $filename[] = $image->getFilename();
        }
        $advantages = [];

        foreach ($carAdges as $advantage){
            $advantages[] = $advantage->getAdvantageName();
        }
        $infos["images"] = $filename;
        $infos["advantages"] = $advantages;
        $infos["imagesURL"] = "https://leyenguema.com/compagnies_logo/";
        return $infos;
    }
}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Entity\CarAdvantages;
use App\Entity\ParkAuto;
use App\Form\CarFormType;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Notifier\Notification\Notification;
use Symfony\Component\Notifier\NotifierInterface;
use Symfony\Component\Routing\Annotation\Route;

class CarController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    /**
     * CarController constructor.
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/car/new_car/{id}-new-car-{csrf}", name="new_car")
     * @param Request $request
     * @param ParkAuto $parkAuto
     * @param FileUploader $fileUploader
     * @param NotifierInterface $notifier
     * @param string $csrf
     * @return Response
     */
    public function new_car(Request $request, ParkAuto $parkAuto, FileUploader $fileUploader, NotifierInterface $notifier, string $csrf): Response
    {
        $car = new Car();
        $form = $this->createForm(CarFormType::class, $car);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $car->setParkAuto($parkAuto)
                ->setCreatedAt(new \DateTime('now'))
                ->setSaleState(false);
            $car_advantages = $form['carAdvantages']->getData();
            foreach ($car_advantages as $car_advantage){
                $carAdvantage = new CarAdvantages();
                $carAdvantage->setAdvantageName($car_advantage);
                $car->addCarAdvantage($carAdvantage);
            }
            if($images = $form['carImages']->getData()){
                $fileUploader->uploads($images, $car);
            }
            $this->entityManager->persist($car);
            $this->entityManager->flush();
            $notifier->send(new Notification("Le véhicule a été ajouté avec succès !", ['browser']));
            return $this->redirectToRoute('park_auto_owner_page', [
                'id'=>$parkAuto->getId(),
                'csrf'=>$csrf
            ]);
        }

        return $this->render('car/new_car.html.twig', [
            'form' => $form->createView(),
            'car'=>$car
        ]);
    }

    /**
     * @param Car $car
     * @return Response
     * @Route("/car/car_details/{id}-{csrf}", name="car_details")
     */
    public function car_details(Car $car):Response{
        return $this->render('/car/car_details.html.twig', [
            'car'=>$car
        ]);
    }

    /**
     * @param Car $car
     * @param Request $request
     * @param NotifierInterface $notifier
     * @param string $csrf
     * @param FileUploader $fileUploader
     * @return Response
     * @Route("/car/car_edit/{id}-car-edit-{csrf}", name="car_edit")
     */
    public function edit_car(Car $car, Request $request, NotifierInterface $notifier, string $csrf, FileUploader $fileUploader):Response{
        $form = $this->createForm(CarFormType::class, $car);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $car->setCreatedAt(new \DateTime('now'));
            $car_advantages = $form['carAdvantages']->getData();
            foreach ($car_advantages as $car_advantage){
                $carAdvantage = new CarAdvantages();
                $carAdvantage->setAdvantageName($car_advantage);
                $car->addCarAdvantage($carAdvantage);
            }
            if($images = $form['carImages']->getData()){
                $fileUploader->uploads($images, $car);
            }
            $this->entityManager->flush();
            $notifier->send(new Notification("Votre véhicule a été modifié avec succès !", ['browser']));
            return $this->redirectToRoute('park_auto_owner_page', [
                'id'=>$car->getParkAuto()->getId(),
                'csrf'=>$csrf
            ]);
        }
        return $this->render('car/car_edit.html.twig', [
            'form' => $form->createView(),
            'car'=>$car
        ]);
    }

    /**
     * @param Car $car
     * @param Request $request
     * @param FileUploader $fileUploader
     * @param NotifierInterface $notifier
     * @param string $csrf
     * @return Response
     * @Route("car/delete_car/{id}-deletion-{csrf}", name="delete_car")
     */
    public function delete_car(Car $car, Request $request, FileUploader $fileUploader, NotifierInterface $notifier, string $csrf):Response{
        if($this->isCsrfTokenValid('delete'.$car->getId(), $request->get('_token'))){
            foreach ($car->getCarImages() as $carImage){
                $fileUploader->delete($carImage->getFilename());
            }
            $this->entityManager->remove($car);
            $this->entityManager->flush();
            $notifier->send(new Notification("Votre véhicule a bien été supprimé !", ['browser']));
            return $this->redirectToRoute('park_auto_owner_page', [
                'id'=>$car->getParkAuto()->getId(),
                'csrf'=>$csrf
            ]);
        }
        return $this->redirectToRoute('park_auto_owner_page', [
            'id'=>$car->getParkAuto()->getId(),
            'csrf'=>$csrf
        ]);
    }

    /**
     * @param Car $car
     * @return Response
     * @Route("/car/change_sale_state/{id}", name="change_sale_state")
     */
    public function change_sale_state(Car $car):Response{
        $car->setSaleState(!$car->getSaleState());
        $this->entityManager->flush();
        return $this->json(["status"=>"Ok", "sale_state"=>$car->getSaleState()]);
    }
}

templates/car/__car_card.html.twig
<div class="__card">
    <div class="__park_auto_image">
        <img src="{{ asset('companies_logo/'~car.getCarImages[random(0, car.getCarImages|length-1)].getFilename()) }}" alt="logo image">
    </div>
    <div class="park_auto_card_body">
        <div class="__car_mark_price_block">
            <h5 class="__myPolice">
                <a href="{{ path('car_details', { id: car.id, csrf: csrf_token('car_details'~car.getSlug()) }) }}" style="color: #0d41a1;">
                    {{ car.carBrand }}
                </a>
            </h5>
            <h4 class="__myPolice" style="color: #0d41a1; text-align: end;">{{ car.carPrice | number_format(0, ' ', ' ')}} FG</h4>
        </div>
        <h6 class="__myPolice text-muted"> {{ car.carModel }} </h6>
        <span style="font-family: 'UTMCaviar'">{{ car.carYear }}</span><span class="__myPolice" style="font-size: 24px;">.</span>
        <span>{{ car.fuel }}</span><span class="__myPolice" style="font-size: 24px;">.</span>
        <span>{{ car.mileage|number_format(0, ' ', ' ') }} km</span><span class="__myPolice" style="font-size: 24px;">.</span>
        <span>{{ car.transmissionType }}</span>
    </div>
</div>

templates/car/__car_card_profile.html.twig
<div class="__card">
    <div class="__park_auto_image">
        <img src="{{ asset('companies_logo/'~car.getCarImages[random(0, car.getCarImages|length-1)].getFilename()) }}" alt="logo image">
    </div>
    <div class="park_auto_card_body">
        <div class="__car_mark_price_block">
            <h5 class="__myPolice">
                <a href="{{ path('car_details', { id: car.id, csrf: csrf_token('car_details'~car.getSlug()) }) }}" style="color: #0d41a1;">
                    {{ car.carBrand }}
                </a>
            </h5>
            <h5 class="__myPolice" style="color: #0d41a1; text-align: end;">{{ car.carPrice | number_format(0, ' ', ' ')}} FG</h5>
        </div>
        <h6 class="__myPolice text-muted"> {{ car.carModel }} </h6>
        <span style="font-family: 'UTMCaviar'">{{ car.carYear }}</span><span class="__myPolice" style="font-size: 24px;">.</span>
        <span>{{ car.fuel }}</span><span class="__myPolice" style="font-size: 24px;">.</span>
        <span>{{ car.mileage }} km</span><span class="__myPolice" style="font-size: 24px;">.</span>
        <span>{{ car.transmissionType }}</span>
        <div class="__car_owner_int">
            <a class="btn btn-sm btn-info __myPolice" href="{{ path('car_edit', { id:car.id, csrf:csrf_token('owner_page'~car.parkAuto.getSlug()) }) }}"><i class="fas fas fa-edit"></i></a>
            <button class="btn btn-sm btn-info __myPolice" id="sale_state_btn" data-route="{{ path('change_sale_state', { id:car.id }) }}" data-id="{{ car.id }}">
                {% if car.saleState %}
                    Vendu
                {% else %}
                    Non Vendu
                {% endif %}
            </button>
            <form method="post" action="{{ path('delete_car', { id:car.id, csrf:csrf_token('owner_page'~car.parkAuto.getSlug()) }) }}" style="display: inline-block;" onsubmit="return confirm('Êtes-vous sûr ?')">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="_token" value="{{ csrf_token('delete'~car.id) }}">
                <button type="submit" class="btn btn-sm btn-danger __myPolice mb-2" ><i class="fas fas fa-trash-alt"></i></button>
            </form>
        </div>
    </div>
</div>

templates/car/__new_car_form.html.twig
{{ form_start(form) }}
<div class="adRegisterRow">
    <div class="adInputColumn">
        {{ form_label(form.car_brand, "Donnez la marque *") }}
        {{ form_widget(form.car_brand) }}
    </div>
    <div class="adInputColumn">
        {{ form_label(form.car_model, "Donnez le modèle *") }}
        {{ form_widget(form.car_model) }}
    </div>
    <div class="adInputColumn">
        {{ form_label(form.fuel, "Selectionnez le type de carburant *") }}
        {{ form_widget(form.fuel) }}
    </div>
</div>
<div class="adRegisterRow">
    <div class="adInputColumn">
        {{ form_label(form.mileage, "Donnez le kilométrage *") }}
        {{ form_widget(form.mileage) }}
    </div>
    <div class="adInputColumn">
        {{ form_label(form.car_year, "Donnez l'année du véhicule *") }}
        {{ form_widget(form.car_year) }}
    </div>
    <div class="adRegisterRow">
        <div class="adInputColumn-1">
            {{ form_label(form.car_country, "Donnez le pays d'origine *") }}
            {{ form_widget(form.car_country) }}
        </div>
    </div>
</div>
<div class="adRegisterRow">
    <div class="adInputColumn">
        {{ form_label(form.car_class, "Selectionnez la classe du véhicule *") }}
        {{ form_widget(form.car_class) }}
    </div>
    <div class="adInputColumn">
        {{ form_label(form.car_nb_places, "Donnez le nombre de places *") }}
        {{ form_widget(form.car_nb_places) }}
    </div>
    <div class="adInputColumn">
        {{ form_label(form.car_nb_doors, "Donnez le nombre de portes *") }}
        {{ form_widget(form.car_nb_doors) }}
    </div>
</div>
<div class="adRegisterRow">
    <div class="adInputColumn">
        {{ form_label(form.car_color, "Donnez la couleur *") }}
        {{ form_widget(form.car_color) }}
    </div>
    <div class="adInputColumn">
        {{ form_label(form.car_price, "Donnez votre prix *") }}
        {{ form_widget(form.car_price) }}
    </div>
    <div class="adInputColumn">
        {{ form_label(form.car_state, "Selectionnez l'état du véhicule *") }}
        {{ form_widget(form.car_state) }}
    </div>
</div>
<div class="adRegisterRow">
    <div class="adInputColumn">
        {{ form_label(form.transmissionType, "Selectionnez le type de transmission *") }}
        {{ form_widget(form.transmissionType) }}
    </div>
    <div class="adInputColumn">
        {{ form_label(form.carAdvantages, "Selectionnez les points forts du véhicule *") }}
        {{ form_widget(form.carAdvantages) }}
    </div>
</div>
<div class="adRegisterRow">
    <div class="adInputColumn-1">
        {{ form_label(form.carImages, "Télécharchez les images *") }}
        {{ form_widget(form.carImages) }}
    </div>
</div>
<div class="adRegisterRow">
    <div class="__list_images">
        {% for image in car.carImages %}
            <div class='__car_images_form'>
                <img src="{{ asset('companies_logo/'~image.filename) }} " alt="image">
            </div>
        {% endfor %}
    </div>
</div>

<div class="newActRegisterRow">
    <button id="submit_btn" class="validate_btn btn btn-rounded btn-block" type="submit">Ajouter</button>
</div>
{{ form_end(form) }}

templates/car/car_details.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ car.carBrand }}-{{ car.carModel }}-{{ car.carYear }}{% endblock %}

{% block body %}
    <main class="__main_page">
        <main class="__container_car">
            <div class="__details_block">
                <div class="__car_images_block" data-nb_img="{{ car.carImages | length }}" id="items">
                    <div class="__slides">
                        {% for image in car.carImages %}
                            <div class='__slide_item'>
                                <img src="{{ asset('companies_logo/'~image.filename) }} " alt="image">
                            </div>
                        {% endfor %}
                    </div>
                    <a class="__left">&#10094;</a>
                    <a class="__right">&#10095;</a>
                </div>
                <div class="__dot_control">
                    {% for image in car.carImages %}
                        <span class="dot" data-index="{{ loop.index }}"></span>
                    {% endfor %}
                </div>
                <div class="__car_details">
                    <div class="__car_mark_price_block">
                        <h3 class="__myPolice" style="color: #0d41a1;">
                            {{ car.carBrand }} {{ car.carModel }}
                        </h3>
                        <h4 class="__myPolice" style="color: #0d41a1; text-align: end;">{{ car.carPrice | number_format(0, ' ', ' ')}} FG</h4>
                    </div>
                    <h3 class="__myPolice" style="color: #0d41a1;">Caractéristiques</h3>
                    <ul class="list-unstyled __list_group_v1">
                        <li class="__list_group_item_v1">{{ car.carBrand }}</li>
                        <li class="__list_group_item_v1">{{ car.carModel }}</li>
                        <li class="__list_group_item_v1">Carburant : {{ car.fuel }}</li>
                        <li class="__list_group_item_v1">{{ car.carClass }}</li>
                        <li class="__list_group_item_v1">{{ car.carYear }}</li>
                        <li class="__list_group_item_v1">{{ car.mileage | number_format(0, ' ', ' ')}} km</li>
                        <li class="__list_group_item_v1">{{ car.carNbPlaces }} places</li>
                        <li class="__list_group_item_v1">{{ car.carNbDoors }} portières</li>
                        <li class="__list_group_item_v1">Couleur : {{ car.carColor }} </li>
                        <li class="__list_group_item_v1">Etat : {{ car.carState }} </li>
                        <li class="__list_group_item_v1">Transimission : {{ car.transmissionType }} </li>
                    </ul>
                    <h3 class="__myPolice" style="color: #0d41a1;">Les points forts</h3>
                    <ul class="list-unstyled __list_group_v1">
                        {% for adv in car.carAdvantages %}
                            <li class="__list_group_item_v1">{{ adv.advantageName }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </main>
    </main>
    {% include '__footer.html.twig' %}
    {% block javascripts %}
        {{ encore_entry_script_tags('__slide_control') }}
        {{ encore_entry_script_tags('menu_handler') }}
    {% endblock %}
{% endblock %}

templates/car/car_edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Modification des informations du véhicule{% endblock %}

{% block body %}
    <div class="__container_form">
        <div class="formBox">
            <div class="__announcement"><h5><i class="fas fa-plus-square"></i> Modification des informations du véhicule</h5></div>
            {% include 'car/__new_car_form.html.twig' %}
        </div>
    </div>
    {% include '__footer.html.twig' %}
{% endblock %}

templates/car/new_car.html.twig
{% extends 'base.html.twig' %}
{% block title %}Ajout de nouveau véhicule{% endblock %}

{% block body %}
    <div class="__container_form">
        <div class="formBox">
            <div class="__announcement"><h5><i class="fas fa-plus-square"></i> Ajouter de nouveau véhicule</h5></div>
            {% include 'car/__new_car_form.html.twig' %}
        </div>
    </div>
    {% include '__footer.html.twig' %}
{% endblock %}