src/Entity/Admin.php
<?php

namespace App\Entity;

use App\Repository\AdminRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AdminRepository::class)
 */
class Admin implements UserInterface, \Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank
     * @Assert\Length(min=10)
     * @Assert\Regex("/^[a-zA-z\s]+$/")
     */
    private $adminname;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\EqualTo(propertyPath="confirm_password")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password")
     * @var string
     */
    private string $confirm_password;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern="/^[6][2-9][0-9][0-9]{2}[0-9]{2}[0-9]{2}$/",
     *     match=true,
     *     message="Le numero de Tel doit contenir que des nombres"
     * )
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="datetime")
     */
    private $registerAt;

    /**
     * @ORM\OneToOne(targetEntity=AdminAvatar::class, mappedBy="userAvatar", cascade={"persist", "remove"})
     */
    private $userAvatar;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getConfirmPassword(): string
    {
        return $this->confirm_password;
    }

    /**
     * @param string $confirm_password
     */
    public function setConfirmPassword(string $confirm_password): void
    {
        $this->confirm_password = $confirm_password;
    }

    public function getAdminname(): ?string
    {
        return $this->adminname;
    }

    public function setAdminname(string $adminname): self
    {
        $this->adminname = $adminname;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->adminname;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_ADMIN';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getRegisterAt(): ?\DateTimeInterface
    {
        return $this->registerAt;
    }

    public function setRegisterAt(\DateTimeInterface $registerAt): self
    {
        $this->registerAt = $registerAt;

        return $this;
    }

    public function __toString():string{
        return $this->adminname;
    }

    public function getUserAvatar(): ?AdminAvatar
    {
        return $this->userAvatar;
    }

    public function setUserAvatar(AdminAvatar $userAvatar): self
    {
        // set the owning side of the relation if necessary
        if ($userAvatar->getUserAvatar() !== $this) {
            $userAvatar->setUserAvatar($this);
        }

        $this->userAvatar = $userAvatar;

        return $this;
    }

    public function getUserIdentifier(): string
    {
        // TODO: Implement getUserIdentifier() method.
    }
}

src/Entity/Studio.php
<?php

namespace App\Entity;

use App\Repository\StudioRepository;
use App\Tools\EntityInfos;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=StudioRepository::class)
 */
class Studio implements EntityInfos
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $property_type;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\NotBlank
     */
    private $property_surface;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\NotBlank
     */
    private $piece_number;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\NotBlank
     */
    private $bathroom;

    /**
     * @ORM\Column(type="boolean")
     */
    private $flatsharing;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\NotBlank
     */
    private $furniture;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $proposition_type;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $municipality;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $more_infos_address;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $other_infos;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Regex(
     *     pattern="/^[6][2-9][0-9][0-9]{2}[0-9]{2}[0-9]{2}$/",
     *     match=true,
     *     message="Le numero de Tel doit contenir que des nombres et doit être de la forme 6xxxxxxxx"
     * )
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $ad_title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $equipements;



    /**
     * @ORM\OneToMany(targetEntity=StudioImages::class, mappedBy="studio", orphanRemoval=true, cascade={"persist"})
     */
    private $studioImages;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="studios")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $district;

    public function __construct()
    {
        $this->studioImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPropertyType(): ?string
    {
        return $this->property_type;
    }

    public function setPropertyType(string $property_type): self
    {
        $this->property_type = $property_type;

        return $this;
    }

    public function getPropertySurface(): ?int
    {
        return $this->property_surface;
    }

    public function setPropertySurface(int $property_surface): self
    {
        $this->property_surface = $property_surface;

        return $this;
    }

    public function getPieceNumber(): ?int
    {
        return $this->piece_number;
    }

    public function setPieceNumber(int $piece_number): self
    {
        $this->piece_number = $piece_number;

        return $this;
    }

    public function getBathroom(): ?bool
    {
        return $this->bathroom;
    }

    public function setBathroom(bool $bathroom): self
    {
        $this->bathroom = $bathroom;

        return $this;
    }

    public function getFlatSharing(): ?bool
    {
        return $this->flatsharing;
    }

    public function setFlatSharing(bool $boolean): self
    {
        $this->flatsharing = $boolean;

        return $this;
    }

    public function getFurniture(): ?bool
    {
        return $this->furniture;
    }

    public function setFurniture(bool $furniture): self
    {
        $this->furniture = $furniture;

        return $this;
    }

    public function getPropositionType(): ?string
    {
        return $this->proposition_type;
    }

    public function setPropositionType(string $proposition_type): self
    {
        $this->proposition_type = $proposition_type;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getMunicipality(): ?string
    {
        return $this->municipality;
    }

    public function setMunicipality(string $municipality): self
    {
        $this->municipality = $municipality;

        return $this;
    }

    public function getMoreInfosAddress(): ?string
    {
        return $this->more_infos_address;
    }

    public function setMoreInfosAddress(string $more_infos_address): self
    {
        $this->more_infos_address = $more_infos_address;

        return $this;
    }

    public function getOtherInfos(): ?string
    {
        return $this->other_infos;
    }

    public function setOtherInfos(?string $other_infos): self
    {
        $this->other_infos = $other_infos;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAdTitle(): ?string
    {
        return $this->ad_title;
    }

    public function setAdTitle(string $at_title): self
    {
        $this->ad_title = $at_title;

        return $this;
    }

    public function getEquipements(): ?string
    {
        return $this->equipements;
    }

    public function setEquipements(?string $equipements): self
    {
        $this->equipements = $equipements;

        return $this;
    }

    /**
     * @return Collection|StudioImages[]
     */
    public function getStudioImages(): Collection
    {
        return $this->studioImages;
    }

    public function addStudioImage(StudioImages $studioImage): self
    {
        if (!$this->studioImages->contains($studioImage)) {
            $this->studioImages[] = $studioImage;
            $studioImage->setStudio($this);
        }

        return $this;
    }

    public function removeStudioImage(StudioImages $studioImage): self
    {
        if ($this->studioImages->removeElement($studioImage)) {
            // set the owning side to null (unless already changed)
            if ($studioImage->getStudio() === $this) {
                $studioImage->setStudio(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDistrict(): ?string
    {
        return $this->district;
    }

    public function setDistrict(string $district): self
    {
        $this->district = $district;

        return $this;
    }
    public function getSlug():string{
        return (new Slugify())->slugify($this->ad_title);
    }

    public function getInfos(): array{
        $infos = [];
        foreach ($this as $item=>$value){
            if($item != "user" and $item != "studioImages") {
                $infos[$item] = $value;
            }
        }
        $filename = [];
        foreach ($this->getStudioImages() as $image){
            $filename[] = $image->getFilename();
        }
        $infos["images"] = $filename;
        $infos["imagesURL"] = "https://leyenguema.com/compagnies_logo/";
        return $infos;
    }
}

templates/studio/__studio_card.html.twig
<div class="__card">
    <div class="__prop_card_image">
        <img src="{{ asset('companies_logo/'~studio.getStudioImages[random(0, studio.getStudioImages|length-1)].getFilename()) }}" alt="logo image">
    </div>
    <div class="__prop_card_body">
        <p>
            <span class="badge badge-primary">Studio <i class="fas fa-arrow-right"></i> </span>
            {{ studio.propertySurface }} <span class="badge badge-danger">m²</span>
            {{ studio.pieceNumber }} <i class="fas fa-bed"></i>
            {{ studio.bathroom }} <i class="fas fa-bath"></i>
            {% if studio.propositionType == 'A louer' %}
                <span class="badge badge-danger">En location</span>
            {% else %}
                <span class="badge badge-danger">En Vente</span>
            {% endif %}
        </p>
        <h5 class="__myPolice">{{ studio.adTitle }}</h5>
        <p>Meublé <span class="badge badge-danger">
                        {% if studio.furniture %} Oui {% else %} Non {% endif %}
                    </span></p>
        <p>{{ studio.city }}|{{ studio.municipality }}|{{ studio.district }}</p>
        <div class="__prop_price">{{ studio.price | format_number }} FG {% if studio.propositionType == 'A louer' %}/mois {% endif %}</div>
        <p class="__myPolice" style="text-align: end"><a href="{{ path('studio_details', { id:studio.id, slug:csrf_token('studio'~studio.getSlug()) }) }}" style="color: #0d41a1;"><i class="fas fa-eye"></i> Voire le studio</a></p>
        <hr>
        <div class="__prop_owner_avatar">
            <img src="{% if studio.user.useravatar %}
                            {{ asset('images/users_avatar/'~studio.user.useravatar.imageName) }}
                        {% else %}
                            {{ asset('images/avatar_def.png') }}
                      {% endif %}"
                 alt="">
            <p>{{ studio.user.username }}</p>
        </div>
    </div>
</div>

templates/studio/__studio_card_profile.html.twig
<div class="__card">
    <div class="__prop_card_image">
        <img src="{{ asset('companies_logo/'~studio.getStudioImages[random(0, studio.getStudioImages|length-1)].getFilename()) }}" alt="logo image">
    </div>
    <div class="__prop_card_body">
        <p>
            {{ studio.propertySurface }} <span class="badge badge-danger">m²</span>
            {{ studio.pieceNumber }} <i class="fas fa-bed"></i>
            {{ studio.bathroom }} <i class="fas fa-bath"></i>
        </p>
        <h5 class="__myPolice">{{ studio.adTitle }}</h5>
        <p>{{ studio.city }}|{{ studio.municipality }}|{{ studio.district }}</p>
        <p style="text-align: end">{{ studio.createdAt | format_datetime('full', 'none', locale='fr') }} <i class="fas fa-calendar"></i></p>
        <div class="__prop_price">{{ studio.price | format_number }} FG {% if studio.propositionType == 'A louer' %}/mois {% endif %}</div>
        <hr>
        <form method="post" action="{{ path('delete_studio', { id:studio.id, user:app.user.id, slug:csrf_token('_user'~app.user.getSlug()) }) }}" style="display: inline-block;" onsubmit="return confirm('Êtes-vous sûr ?')">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token('delete'~studio.id) }}">
            <button type="submit" class="btn btn-sm btn-danger __myPolice mb-2" ><i class="fas fas fa-trash-alt"></i></button>
        </form>
    </div>
</div>

templates/studio/__studio_form.html.twig
{{ form_start(form) }}
<div class="__bloc">
    <div class="__announcement"><h5><i class="fas fa-plus-square"></i> Caractéristiques de base du studio </h5></div>
    <div class="__row-3">
        <div class="_column">
            {{ form_label(form.ad_title, "Titre de l'annonce") }}
            {{ form_widget(form.ad_title) }}
        </div>
        <div class="_column">
            {{ form_label(form.property_type, "Le type de studio") }}
            {{ form_widget(form.property_type) }}
        </div>
        <div class="_column">
            {{ form_label(form.property_surface, "Surface en m²") }}
            {{ form_widget(form.property_surface) }}
        </div>
    </div>
    <div class="__row-2">
        <div class="_column">
            {{ form_label(form.piece_number, "Nombre de pièces") }}
            {{ form_widget(form.piece_number) }}
        </div>
        <div class="_column">
            {{ form_label(form.bathroom, "Nombre de salles de bain") }}
            {{ form_widget(form.bathroom) }}
        </div>
    </div>
</div>
<div class="__bloc">
    <div class="__row-2">
        <div class="_column">
            {{ form_label(form.furniture, "Le studio est-il meublé ?") }}
            {{ form_widget(form.furniture) }}
        </div>
        <div class="_column">
            {{ form_label(form.flatsharing, "Le studio est en colocation ?") }}
            {{ form_widget(form.flatsharing) }}
        </div>
    </div>
    <div class="__row-2">
        <div class="_column">
            {{ form_label(form.equipements, "Citer tous les equipements et meubles se trouvant dans le studio ") }}
            {{ form_widget(form.equipements) }}
        </div>
        <div class="_column">
            {{ form_label(form.other_infos, "Autres details sur le studio le mettant en valeur") }}
            {{ form_widget(form.other_infos) }}
        </div>
    </div>
</div>
<div class="__bloc">
    <p>
        Le studio est à vendre ou à louer ?<br>
        Choisissez-en et donner votre prix sans espace entre les chiffres
    </p>
    <div class="_column">
        {{ form_label(form.proposition_type, "Type de proposition") }}
        {{ form_widget(form.proposition_type) }}
    </div>
    <div class="_column">
        {{ form_label(form.price, "Prix") }}
        {{ form_widget(form.price) }}
    </div>
</div>
<div class="__bloc">
    <div class="__announcement"><h5><i class="fas fa-plus-square"></i> Où se trouve ce studio ?</h5></div>
    <p>
        Les moindres details sur l'adresse sont necessaires et importants pour mieux localiser votre studio.
        Vous pouvez aussi indiquer la proximité des transports en commun ou des routes principales ou encore des lieux
        <br>
        comme les gares et les aéroports ou des commerces, restaurants et services médicaux (médecins, hôpitaux, cliniques, etc.) <br>
        Décrivez le quartier si c’est un point positif (résidentiel, calme, tranquille)
    </p>
    <div class="__row-3">
        <div class="_column">
            {{ form_label(form.city, "La ville") }}
            {{ form_widget(form.city) }}
        </div>
        <div class="_column">
            {{ form_label(form.municipality, "La commune") }}
            {{ form_widget(form.municipality) }}
        </div>
        <div class="_column">
            {{ form_label(form.district, "Le quartier") }}
            {{ form_widget(form.district) }}
        </div>
    </div>
    <div class="__row-1">
        <div class="_column">
            {{ form_label(form.more_infos_address, "Complement de la localisation") }}
            {{ form_widget(form.more_infos_address) }}
        </div>
    </div>
</div>
<div class="__bloc">
    <div class="_column">
        {{ form_label(form.phone_number, "Donner votre numéro de téléphone") }}
        {{ form_widget(form.phone_number) }}
    </div>
    <div class="_column">
        {{ form_label(form.email, "Donner votre email (facultatif)") }}
        {{ form_widget(form.email) }}
    </div>
</div>
<div class="__bloc">
    <div class="__row-1">
        <div class="_column">
            {{ form_label(form.studioImages, "Images") }}
            {{ form_widget(form.studioImages) }}
        </div>
    </div>
</div>

<div class="next_step_btn_box">
    <button id="prev_btn" class="validate_btn btn" type="button">precedent</button>
    <button id="submit_btn" class="validate_btn btn" type="button">Suivant</button>
</div>
{{ form_end(form) }}

templates/studio/all_studios.html.twig
{% extends 'base.html.twig' %}

{% block title %}Studios{% endblock %}

{% block body %}
    <main class="__main">
        <div class="__items">
            <div class="bg-light __response_box mt-4">
                {{ form_start(form_search, {'attr':{'id': 'formSearchAd', 'action':path('apart_search')}}) }}
                <div class="formAdsSearchColumn">
                    {{ form_widget(form_search.location) }}
                </div>
                <div class="formAdsSearchColumn">
                    {{ form_widget(form_search.price) }}
                    <datalist id="addressList"></datalist>
                </div>
                <div class="formAdsSearchColumnBtn">
                    <button id="validate_btn_act" class="btn btn-block" type="submit"><i class="fas fa-search"></i></button>
                </div>
                {{ form_end(form_search) }}
            </div>
            <h4 class="__myPolice" style="text-align: center;"><span class="badge bg-danger">{{ studios | length }}</span>Studios</h4>
            <hr>
            <div class="__item">
                {% for studio in studios %}
                    {% include '/studio/__studio_card.html.twig' with {'studio':studio}  %}
                {% endfor %}
            </div>
            <div class="__navigation">
                <hr class="__line">
                <div class="navigation">
                    {{ knp_pagination_render(studios) }}
                </div>
            </div>
        </div>
    </main>
    {% include '__footer.html.twig' %}
{% endblock %}

templates/studio/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StudioController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'D:/yenguema/src/Controller/StudioController.php'|file_link(0) }}">src/Controller/StudioController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'D:/yenguema/templates/studio/new_application.html.twig'|file_link(0) }}">templates/studio/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/studio/new_studio.html.twig
{% extends 'base.html.twig' %}
{% block title %}Nouveau studio{% endblock %}

{% block body %}
    <div class="__container_form">
        <div class="formBox">
            {% include 'studio/__studio_form.html.twig' %}
        </div>
    </div>
    {% include '__footer.html.twig' %}
    {% block javascripts %}
        {{ encore_entry_script_tags('__form_step_handler') }}
        {{ encore_entry_script_tags('menu_handler') }}
    {% endblock %}
{% endblock %}

templates/studio/studio.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ studio.propertyType }}{% endblock %}

{% block body %}
    <main class="__main_page">
        <main class="__container">
            <div class="__details_block">
                <div id="items" class="__details_property_images_box" data-nb_img="{{ studio.studioImages | length }}">
                    {% for img in studio.studioImages %}
                        <div class="__prop_img_item">
                            <img src="{{ asset('companies_logo/'~img.getFilename()) }}" alt="">
                        </div>
                    {% endfor %}
                    <a class="__left" id="__left">&#10094;</a>
                    <a class="__right" id="__right">&#10095;</a>
                </div>
                <div class="__dot_control">
                    {% for image in studio.studioImages %}
                        <span class="dot" data-index="{{ loop.index }}"></span>
                    {% endfor %}
                </div>
                <div class="__prop_details_body">
                    <h5 class="__myPolice">{{ studio.adTitle }}</h5>
                    <p>
                        {{ studio.propertySurface }} <span class="badge badge-danger">m²</span>
                        {{ studio.pieceNumber }} <i class="fas fa-bed"></i>
                        {{ studio.bathroom }} <i class="fas fa-bath"></i>
                        {% if studio.propositionType == 'A louer' %}
                            <span class="badge badge-danger">En location</span>
                        {% else %}
                            <span class="badge badge-danger">En Vente</span>
                        {% endif %}
                    </p>
                    <p>{{ studio.city }}|{{ studio.municipality }}|{{ studio.district }}</p>
                    <p style="text-align: end">{{ studio.createdAt | format_datetime('full', 'none', locale='fr') }} <i class="fas fa-calendar"></i></p>
                    <div style="display: flex; justify-content: space-between;">
                        <div class="__prop_price">{{ studio.price | format_number }} FG {% if studio.propositionType == 'A louer' %}/mois {% endif %}</div>
                        <div class="__prop_price"><a href="tel:{{ studio.phoneNumber }}" class="text-white"><i class="fas fa-phone-square"></i>Contacter</a></div>
                    </div>
                    <p>Meublé <span class="badge badge-danger">
                        {% if studio.furniture %} Oui {% else %} Non {% endif %}
                    </span></p>
                    <p>En colocation <span class="badge badge-danger">
                        {% if studio.flatsharing %} Oui {% else %} Non {% endif %}
                    </span></p>
                    <h6 class="__myPolice">Plus sur l'adresse...</h6>
                    <p>{{ studio.moreInfosAddress | raw }}</p>
                    {% if studio.equipements %}
                        <h6 class="__myPolice">Equipements du studio</h6>
                        <p>{{ studio.equipements|raw }}</p>
                    {% endif %}
                    {% if studio.otherInfos %}
                        <h6 class="__myPolice">Autres informations</h6>
                        <p>{{ studio.otherInfos|raw }}</p>
                    {% endif %}
                    <hr>
                    <h6 class="__myPolice">Annonceur</h6>
                    <div class="__prop_owner_avatar">
                        <img src="{% if studio.user.useravatar %}
                            {{ asset('images/users_avatar/'~studio.user.useravatar.imageName) }}
                        {% else %}
                            {{ asset('images/avatar_def.png') }}
                      {% endif %}"
                             alt="">
                        <p>{{ studio.user.username }}</p>
                    </div>
                </div>
            </div>
        </main>
    </main>
    {% include '__footer.html.twig' %}
    {% block javascripts %}
        {{ encore_entry_script_tags('menu_handler') }}
        {{ encore_entry_script_tags('property_slide_images') }}
    {% endblock %}
{% endblock %}

templates/studio/studios.html.twig
{% extends 'base.html.twig' %}
{% block title %}Studios{% endblock %}

{% block body %}
    <main class="__main">
        <div class="__items">
            <h4 class="__myPolice" style="text-align: center;">Vos annonces <span class="badge bg-danger">{{ results | length }}</span></h4>
            <hr class="__line">
            <div class="__new">
                <a href="{{ path("new_studio", { id: app.user.getId() }) }}"><i class="fas fa-plus-square"></i> Ajouter une annonce</a>
            </div>
            <div class="__item">
                {% for studio in results %}
                    {% include '/studio/__studio_card_profile.html.twig' with {'studio':studio}  %}
                {% endfor %}
            </div>
        </div>
    </main>
    {% include '__footer.html.twig' %}
{% endblock %}