src/Entity/Admin.php
<?php

namespace App\Entity;

use App\Repository\AdminRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AdminRepository::class)
 */
class Admin implements UserInterface, \Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank
     * @Assert\Length(min=10)
     * @Assert\Regex("/^[a-zA-z\s]+$/")
     */
    private $adminname;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\EqualTo(propertyPath="confirm_password")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password")
     * @var string
     */
    private string $confirm_password;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern="/^[6][2-9][0-9][0-9]{2}[0-9]{2}[0-9]{2}$/",
     *     match=true,
     *     message="Le numero de Tel doit contenir que des nombres"
     * )
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="datetime")
     */
    private $registerAt;

    /**
     * @ORM\OneToOne(targetEntity=AdminAvatar::class, mappedBy="userAvatar", cascade={"persist", "remove"})
     */
    private $userAvatar;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getConfirmPassword(): string
    {
        return $this->confirm_password;
    }

    /**
     * @param string $confirm_password
     */
    public function setConfirmPassword(string $confirm_password): void
    {
        $this->confirm_password = $confirm_password;
    }

    public function getAdminname(): ?string
    {
        return $this->adminname;
    }

    public function setAdminname(string $adminname): self
    {
        $this->adminname = $adminname;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->adminname;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_ADMIN';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getRegisterAt(): ?\DateTimeInterface
    {
        return $this->registerAt;
    }

    public function setRegisterAt(\DateTimeInterface $registerAt): self
    {
        $this->registerAt = $registerAt;

        return $this;
    }

    public function __toString():string{
        return $this->adminname;
    }

    public function getUserAvatar(): ?AdminAvatar
    {
        return $this->userAvatar;
    }

    public function setUserAvatar(AdminAvatar $userAvatar): self
    {
        // set the owning side of the relation if necessary
        if ($userAvatar->getUserAvatar() !== $this) {
            $userAvatar->setUserAvatar($this);
        }

        $this->userAvatar = $userAvatar;

        return $this;
    }

    public function getUserIdentifier(): string
    {
        // TODO: Implement getUserIdentifier() method.
    }
}

src/Entity/HouseVilla.php
<?php

namespace App\Entity;

use App\Repository\HouseVillaRepository;
use App\Tools\EntityInfos;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=HouseVillaRepository::class)
 */
class HouseVilla implements EntityInfos
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $property_type;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern="/[1-9]+/",
     *     match=true,
     *     message="Valeur non valide"
     * )
     * @Assert\NotBlank
     */
    private $property_surface;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Regex(
     *     pattern="/[1-9]+/",
     *     match=true,
     *     message="Valeur non valide"
     * )
     * @Assert\NotBlank
     */
    private $room_number;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Regex(
     *     pattern="/[1-9]+/",
     *     match=true,
     *     message="Valeur non valide"
     * )
     * @Assert\NotBlank
     */
    private $bathroom_number;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Regex(
     *     pattern="/[1-9]+/",
     *     match=true,
     *     message="Valeur non valide"
     * )
     * @Assert\NotBlank
     */
    private $wc_number;

    /**
     * @ORM\Column(type="boolean")
     */
    private $furniture;

    /**
     * @ORM\Column(type="boolean")
     */
    private $courtyard;

    /**
     * @ORM\Column(type="boolean")
     */
    private $fenced;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Regex(
     *     pattern="/(1|2)[0-9]{3}/",
     *     match=true,
     *     message="Valeur non valide"
     * )
     * @Assert\NotBlank
     */
    private $build_year;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Regex(
     *     pattern="/[1-9]+/",
     *     match=true,
     *     message="Valeur non valide"
     * )
     * @Assert\NotBlank
     */
    private $floor_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $proposition_type;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Regex(
     *     pattern="/[1-9]\d+/",
     *     match=true,
     *     message="Valeur non valide"
     * )
     * @Assert\NotBlank
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $municipality;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $district;

    /**
     * @ORM\Column(type="text")
     */
    private $more_infos_address;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $other_infos;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Regex(
     *     pattern="/^[6][2-9][0-9][0-9]{2}[0-9]{2}[0-9]{2}$/",
     *     match=true,
     *     message="Le numero de Tel doit contenir que des nombres et doit être de la forme 6xxxxxxxx"
     * )
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email
     * @Assert\NotBlank
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $equipements;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $ad_title;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="houseVillas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=HouseVillaImages::class, mappedBy="house_villa", orphanRemoval=true, cascade={"persist"})
     */
    private $houseVillaImages;

    public function __construct()
    {
        $this->houseVillaImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPropertyType(): ?string
    {
        return $this->property_type;
    }

    public function setPropertyType(string $property_type): self
    {
        $this->property_type = $property_type;

        return $this;
    }

    public function getPropertySurface(): ?string
    {
        return $this->property_surface;
    }

    public function setPropertySurface(string $property_surface): self
    {
        $this->property_surface = $property_surface;

        return $this;
    }

    public function getRoomNumber(): ?int
    {
        return $this->room_number;
    }

    public function setRoomNumber(int $room_number): self
    {
        $this->room_number = $room_number;

        return $this;
    }

    public function getBathroomNumber(): ?int
    {
        return $this->bathroom_number;
    }

    public function setBathroomNumber(int $bathroom_number): self
    {
        $this->bathroom_number = $bathroom_number;

        return $this;
    }

    public function getWcNumber(): ?int
    {
        return $this->wc_number;
    }

    public function setWcNumber(int $wc_number): self
    {
        $this->wc_number = $wc_number;

        return $this;
    }

    public function getFurniture(): ?bool
    {
        return $this->furniture;
    }

    public function setFurniture(bool $furniture): self
    {
        $this->furniture = $furniture;

        return $this;
    }

    public function getCourtyard(): ?bool
    {
        return $this->courtyard;
    }

    public function setCourtyard(bool $courtyard): self
    {
        $this->courtyard = $courtyard;

        return $this;
    }

    public function getFenced(): ?bool
    {
        return $this->fenced;
    }

    public function setFenced(bool $fenced): self
    {
        $this->fenced = $fenced;

        return $this;
    }

    public function getBuildYear(): ?int
    {
        return $this->build_year;
    }

    public function setBuildYear(int $build_year): self
    {
        $this->build_year = $build_year;

        return $this;
    }

    public function getFloorNumber(): ?int
    {
        return $this->floor_number;
    }

    public function setFloorNumber(int $floor_number): self
    {
        $this->floor_number = $floor_number;

        return $this;
    }

    public function getPropositionType(): ?string
    {
        return $this->proposition_type;
    }

    public function setPropositionType(string $proposition_type): self
    {
        $this->proposition_type = $proposition_type;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getMunicipality(): ?string
    {
        return $this->municipality;
    }

    public function setMunicipality(string $municipality): self
    {
        $this->municipality = $municipality;

        return $this;
    }

    public function getDistrict(): ?string
    {
        return $this->district;
    }

    public function setDistrict(string $district): self
    {
        $this->district = $district;

        return $this;
    }

    public function getMoreInfosAddress(): ?string
    {
        return $this->more_infos_address;
    }

    public function setMoreInfosAddress(string $more_infos_address): self
    {
        $this->more_infos_address = $more_infos_address;

        return $this;
    }

    public function getOtherInfos(): ?string
    {
        return $this->other_infos;
    }

    public function setOtherInfos(?string $other_infos): self
    {
        $this->other_infos = $other_infos;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getEquipements(): ?string
    {
        return $this->equipements;
    }

    public function setEquipements(?string $equipements): self
    {
        $this->equipements = $equipements;

        return $this;
    }

    public function getAdTitle(): ?string
    {
        return $this->ad_title;
    }

    public function setAdTitle(string $ad_title): self
    {
        $this->ad_title = $ad_title;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|HouseVillaImages[]
     */
    public function getHouseVillaImages(): Collection
    {
        return $this->houseVillaImages;
    }

    public function addHouseVillaImage(HouseVillaImages $houseVillaImage): self
    {
        if (!$this->houseVillaImages->contains($houseVillaImage)) {
            $this->houseVillaImages[] = $houseVillaImage;
            $houseVillaImage->setHouseVilla($this);
        }

        return $this;
    }

templates/house_villa/__house_card.html.twig
<div class="__card">
    <div class="__prop_card_image">
        <img src="{{ asset('companies_logo/'~house.getHouseVillaImages[random(0, house.getHouseVillaImages|length-1)].getFilename()) }}" alt="logo image">
    </div>
    <div class="__prop_card_body">
        <p>
            <span class="badge badge-primary">{{ house.propertyType }} <i class="fas fa-arrow-right"></i> </span>
            {{ house.propertySurface }} <span class="badge badge-danger">m²</span>
            {{ house.roomNumber }} <i class="fas fa-bed"></i>
            {{ house.bathroomNumber }} <i class="fas fa-bath"></i>
            {{ house.wcNumber }} <i class="fas fa-toilet"></i>
            {% if house.propositionType == 'A louer' %}
                <span class="badge badge-danger">En location</span>
            {% else %}
                <span class="badge badge-danger">En Vente</span>
            {% endif %}
        </p>
        <h5 class="__myPolice">{{ house.adTitle }}</h5>
        <p>Meublé <span class="badge badge-danger">
                        {% if house.furniture %} Oui {% else %} Non {% endif %}
                    </span> |
            Jardin (cour) <span class="badge badge-danger">
                        {% if house.courtyard %} Oui {% else %} Non {% endif %}
                    </span> |
            Cour fermée <span class="badge badge-danger">
                        {% if house.fenced %} Oui {% else %} Non {% endif %}
                    </span>

        </p>
        <p>{{ house.city }}|{{ house.municipality }}|{{ house.district }}</p>
        <div class="__prop_price">{{ house.price | format_number }} FG {% if house.propositionType == 'A louer' %}/mois {% endif %}</div>
        <p class="__myPolice" style="text-align: end">
            <a href="{{ path('house_details', { id:house.id, slug:csrf_token('house'~house.getSlug()) }) }}" style="color: #0d41a1;">
                <i class="fas fa-eye"></i> Voire la {{ house.propertyType }}
            </a>
        </p>
        <hr>
        <div class="__prop_owner_avatar">
            <img src="{% if house.user.useravatar %}
                            {{ asset('images/users_avatar/'~house.user.useravatar.imageName) }}
                        {% else %}
                            {{ asset('images/avatar_def.png') }}
                      {% endif %}"
                 alt="">
            <p>{{ house.user.username }}</p>
        </div>
    </div>
</div>

templates/house_villa/__house_card_profile.html.twig
<div class="__card">
    <div class="__prop_card_image">
        <img src="{{ asset('companies_logo/'~house.getHouseVillaImages[random(0, house.getHouseVillaImages|length-1)].getFilename()) }}" alt="logo image">
    </div>
    <div class="__prop_card_body">
        <p>
            {{ house.propertySurface }} <span class="badge badge-danger">m²</span>
            {{ house.roomNumber }} <i class="fas fa-bed"></i>
            {{ house.bathroomNumber }} <i class="fas fa-bath"></i>
            {{ house.wcNumber }} <i class="fas fa-toilet"></i>

        </p>
        <h5 class="__myPolice">{{ house.adTitle }}</h5>
        <p>{{ house.city }}|{{ house.municipality }}|{{ house.district }}</p>
        <p style="text-align: end">{{ house.createdAt | format_datetime('full', 'none', locale='fr') }} <i class="fas fa-calendar"></i></p>
        <div class="__prop_price">{{ house.price | format_number }} FG {% if house.propositionType == 'A louer' %}/mois {% endif %}</div>
        <hr>
        <form method="post" action="{{ path('delete_house_villa', { id:house.id, user:app.user.id, slug:csrf_token('_user'~app.user.getSlug()) }) }}" style="display: inline-block;" onsubmit="return confirm('Êtes-vous sûr ?')">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token('delete'~house.id) }}">
            <button type="submit" class="btn btn-sm btn-danger __myPolice mb-2" ><i class="fas fas fa-trash-alt"></i></button>
        </form>
    </div>
</div>

templates/house_villa/__house_form.html.twig
{{ form_start(form) }}
<div class="__bloc">
    <div class="__announcement"><h5><i class="fas fa-plus-square"></i> Caractéristiques de base de la maison/villa</h5></div>
    <div class="__row-4">
        <div class="_column">
            {{ form_label(form.propertyType, "Type de la propriété") }}
            {{ form_widget(form.propertyType) }}
        </div>
        <div class="_column">
            {{ form_label(form.ad_title, "Titre de l'annonce") }}
            {{ form_widget(form.ad_title) }}
        </div>
        <div class="_column">
            {{ form_label(form.property_surface, "Surface en m²") }}
            {{ form_widget(form.property_surface) }}
        </div>
        <div class="_column">
            {{ form_label(form.floor_number, "Nombre d'étages") }}
            {{ form_widget(form.floor_number) }}
        </div>
    </div>
    <div class="__row-4">
        <div class="_column">
            {{ form_label(form.room_number, "Nombre de chambres") }}
            {{ form_widget(form.room_number) }}
        </div>
        <div class="_column">
            {{ form_label(form.bathroom_number, "Nombre de salles de bain") }}
            {{ form_widget(form.bathroom_number) }}
        </div>
        <div class="_column">
            {{ form_label(form.wc_number, "Nombre de salles de WC") }}
            {{ form_widget(form.wc_number) }}
        </div>
        <div class="_column">
            {{ form_label(form.build_year, "Année de construction") }}
            {{ form_widget(form.build_year) }}
        </div>
    </div>
    <div class="__row-1">
        <div class="_column">
            {{ form_label(form.other_infos, "Autres details sur la maison/villa le mettant en valeur") }}
            {{ form_widget(form.other_infos) }}
        </div>
    </div>

</div>
<div class="__bloc">
    <div class="__row-3">
        <div class="_column">
            {{ form_label(form.furniture, "La maison/villa est-elle meublée ?") }}
            {{ form_widget(form.furniture) }}
        </div>
        <div class="_column">
            {{ form_label(form.courtyard, "La maison/villa a-t-elle une cour ?") }}
            {{ form_widget(form.courtyard) }}
        </div>
        <div class="_column">
            {{ form_label(form.fenced, "La maison/villa est-elle cloturée ?") }}
            {{ form_widget(form.fenced) }}
        </div>
    </div>
    <div class="__row-1">
        <div class="_column">
            {{ form_label(form.equipements, "Citer tous les equipements et meubles se trouvant dans la maison/villa") }}
            {{ form_widget(form.equipements) }}
        </div>
    </div>
</div>
<div class="__bloc">
    <p>
        La maison/villa est à vendre ou à louer ?<br>
        Choisissez-en et donner votre prix sans espace entre les chiffres
    </p>
    <div class="_column">
        {{ form_label(form.propositionType, "Type de proposition") }}
        {{ form_widget(form.propositionType) }}
    </div>
    <div class="_column">
        {{ form_label(form.price, "Prix") }}
        {{ form_widget(form.price) }}
    </div>
</div>
<div class="__bloc">
    <div class="__announcement"><h5><i class="fas fa-plus-square"></i> Où se trouve cette maison-villa ?</h5></div>
    <p>
        Les moindres details sur l'adresse sont necessaires et importants pour mieux localiser votre maison-villa.
        Vous pouvez aussi indiquer la proximité des transports en commun ou des routes principales ou encore des lieux
        <br>
        comme les gares et les aéroports ou des commerces, restaurants et services médicaux (médecins, hôpitaux, cliniques, etc.) <br>
        Décrivez le quartier si c’est un point positif (résidentiel, calme, tranquille)
    </p>
    <div class="__row-3">
        <div class="_column">
            {{ form_label(form.city, "La ville") }}
            {{ form_widget(form.city) }}
        </div>
        <div class="_column">
            {{ form_label(form.municipality, "La commune") }}
            {{ form_widget(form.municipality) }}
        </div>
        <div class="_column">
            {{ form_label(form.district, "Le quartier") }}
            {{ form_widget(form.district) }}
        </div>
    </div>
    <div class="__row-1">
        <div class="_column">
            {{ form_label(form.more_infos_address, "Complement de la localisation") }}
            {{ form_widget(form.more_infos_address) }}
        </div>
    </div>
</div>
<div class="__bloc">
    <div class="_column">
        {{ form_label(form.phone_number, "Donner votre numéro de téléphone") }}
        {{ form_widget(form.phone_number) }}
    </div>
    <div class="_column">
        {{ form_label(form.email, "Donner votre email (facultatif)") }}
        {{ form_widget(form.email) }}
    </div>
</div>
<div class="__bloc">
    <div class="__row-1">
        <div class="_column">
            {{ form_label(form.houseVillaImages, "Images") }}
            {{ form_widget(form.houseVillaImages) }}
        </div>
    </div>
</div>

<div class="next_step_btn_box">
    <button id="prev_btn" class="validate_btn btn" type="button">precedent</button>
    <button id="submit_btn" class="validate_btn btn" type="button">Suivant</button>
</div>
{{ form_end(form) }}

templates/house_villa/all_houses.html.twig
{% extends 'base.html.twig' %}
{% block title %}Maisons-Villas{% endblock %}

{% block body %}
    <main class="__main">
        <div class="__items">
            <div class="bg-light __response_box mt-4">
                {{ form_start(form_search, {'attr':{'id': 'formSearchAd', 'action':path('house_search')}}) }}
                <div class="formAdsSearchColumn">
                    {{ form_widget(form_search.location) }}
                </div>
                <div class="formAdsSearchColumn">
                    {{ form_widget(form_search.price) }}
                    <datalist id="addressList"></datalist>
                </div>
                <div class="formAdsSearchColumnBtn">
                    <button id="validate_btn_act" class="btn btn-block" type="submit"><i class="fas fa-search"></i></button>
                </div>
                {{ form_end(form_search) }}
            </div>
            <h4 class="__myPolice" style="text-align: center;"><span class="badge bg-danger">{{ houses | length }}</span>Maisons-villas</h4>
            <hr>
            <div class="__item">
                {% for house in houses %}
                    {% include '/house_villa/__house_card.html.twig' with {'house':house}  %}
                {% endfor %}
            </div>
            <div class="__navigation">
                <hr class="__line">
                <div class="navigation">
                    {{ knp_pagination_render(houses) }}
                </div>
            </div>
        </div>
    </main>
    {% include '__footer.html.twig' %}
{% endblock %}

templates/house_villa/house_villa.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ house.adTitle }}{% endblock %}

{% block body %}
    <main class="__main_page">
        <main class="__container">
            <div class="__details_block">
                <div id="items" class="__details_property_images_box" data-nb_img="{{ house.houseVillaImages | length }}">
                    {% for img in house.houseVillaImages %}
                        <div class="__prop_img_item">
                            <img src="{{ asset('companies_logo/'~img.getFilename()) }}" alt="">
                        </div>
                    {% endfor %}
                    <a class="__left" id="__left">&#10094;</a>
                    <a class="__right" id="__right">&#10095;</a>
                </div>
                <div class="__dot_control">
                    {% for image in house.houseVillaImages %}
                        <span class="dot" data-index="{{ loop.index }}"></span>
                    {% endfor %}
                </div>
                <div class="__prop_details_body">
                    <h5 class="__myPolice">{{ house.adTitle }}</h5>
                    <p>
                        {{ house.propertySurface }} <span class="badge badge-danger">m²</span>
                        {{ house.roomNumber }} <i class="fas fa-bed"></i>
                        {{ house.bathroomNumber }} <i class="fas fa-bath"></i>
                        {{ house.wcNumber }} <i class="fas fa-toilet"></i>
                        {{ house.floorNumber }} <i class="fas fa-building"></i> étages
                        {% if house.propositionType == 'A louer' %}
                            <span class="badge badge-danger">En location</span>
                        {% else %}
                            <span class="badge badge-danger">En Vente</span>
                        {% endif %}
                    </p>
                    <p>
                        Jardin(cour) <span class="badge badge-danger">
                            {% if house.courtyard %} Oui
                            {% else %}
                                Non
                            {% endif %}
                        </span>
                        Cour fermée <span class="badge badge-danger">
                            {% if house.fenced %} Oui
                            {% else %}
                                Non
                            {% endif %}
                        </span>
                        Année : <span class="badge badge-danger">{{ house.buildYear }}</span>
                    </p>
                    <p>{{ house.city }}|{{ house.municipality }}|{{ house.district }}</p>
                    <p style="text-align: end">{{ house.createdAt | format_datetime('full', 'none', locale='fr') }} <i class="fas fa-calendar"></i></p>
                    <div style="display: flex; justify-content: space-between;">
                        <div class="__prop_price">{{ house.price | format_number }} FG {% if house.propositionType == 'A louer' %}/mois {% endif %}</div>
                        <div class="__prop_price"><a href="tel:{{ house.phoneNumber }}" class="text-white"><i class="fas fa-phone-square"></i>Contacter</a></div>
                    </div>
                    <p>Meublé <span class="badge badge-danger">
                        {% if house.furniture %} Oui {% else %} Non {% endif %}
                    </span></p>
                    <h6 class="__myPolice">Plus sur l'adresse...</h6>
                    <p>{{ house.moreInfosAddress | raw }}</p>
                    {% if house.equipements %}
                        <h6 class="__myPolice">Equipements de la {{ house.propertyType }}</h6>
                        <p>{{ house.equipements|raw }}</p>
                    {% endif %}
                    {% if house.otherInfos %}
                        <h6 class="__myPolice">Autres informations</h6>
                        <p>{{ house.otherInfos|raw }}</p>
                    {% endif %}
                    <hr>
                    <h6 class="__myPolice">Annonceur</h6>
                    <div class="__prop_owner_avatar">
                        <img src="{% if house.user.useravatar %}
                            {{ asset('images/users_avatar/'~house.user.useravatar.imageName) }}
                        {% else %}
                            {{ asset('images/avatar_def.png') }}
                      {% endif %}"
                             alt="">
                        <p>{{ house.user.username }}</p>
                    </div>
                </div>
            </div>
        </main>
    </main>
    {% include '__footer.html.twig' %}
    {% block javascripts %}
        {{ encore_entry_script_tags('menu_handler') }}
        {{ encore_entry_script_tags('property_slide_images') }}
    {% endblock %}
{% endblock %}